name: Build Adapter Docker Image

env:
    PLATFORMS: linux/arm64, linux/amd64

on:
    push:
       branches: [ "main" ]
    # pull_request:
    #   branches: [ "main" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{github.ref_name}}

            - name: Get Short SHA
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            # the QEMU emulator lets us build for arm processors also
            # see https://github.com/docker/setup-qemu-action
            - name: Set up QEMU emulator
              uses: docker/setup-qemu-action@v1

            # see https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            # see https://github.com/docker/build-push-action
            - name: Build image and push to DockerHub
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: docker/code-server.dockerfile
                  platforms: ${{ env.PLATFORMS }}

                  # docker hub user/repo:tag
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/mxi-code-server:${{github.ref_name}}-latest
                      ${{ secrets.DOCKERHUB_USERNAME }}/mxi-code-server:${{github.ref_name}}-${{ steps.vars.outputs.sha_short }}

                  # push to docker hub
                  push: true
